field: 64c7eef3-8cb2-40e7-aa91-1178bb428c8f
fieldLayouts:
  d1b2a297-497d-4b97-87a7-d3c68e7bc286:
    tabs:
      -
        elements:
          -
            fieldUid: 5a6ee342-8f4e-49d0-ba14-dab0d1bb937d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 21a696f1-b30d-4e0b-97fd-2d17c3fc56f4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ccff40cb-ef8a-4065-9ac3-101a37a76048
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 016a3355-f383-454b-9c53-fa7ce97d1444
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: afba3105-42e7-4d29-870d-0d17b990599b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  016a3355-f383-454b-9c53-fa7ce97d1444:
    contentColumnType: text
    fieldGroup: null
    handle: position
    instructions: Position
    name: Position
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  21a696f1-b30d-4e0b-97fd-2d17c3fc56f4:
    contentColumnType: datetime
    fieldGroup: null
    handle: dateStarted
    instructions: ''
    name: 'Date Started'
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: true
      showTime: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  5a6ee342-8f4e-49d0-ba14-dab0d1bb937d:
    contentColumnType: text
    fieldGroup: null
    handle: company
    instructions: 'Enter company name'
    name: Company
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  afba3105-42e7-4d29-870d-0d17b990599b:
    contentColumnType: text
    fieldGroup: null
    handle: jobDesription
    instructions: 'enter job description.'
    name: 'Job Desription'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ccff40cb-ef8a-4065-9ac3-101a37a76048:
    contentColumnType: datetime
    fieldGroup: null
    handle: dateEnded
    instructions: ''
    name: 'Date Ended'
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: true
      showTime: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
handle: workplace
name: Workplace
sortOrder: 1
