enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  667cb511-30fb-4ebb-a5d5-15092478136b:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
