enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  667cb511-30fb-4ebb-a5d5-15092478136b:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
